version: '3.9' # Actualizado a una versión más reciente

services:
  db:
    image: mysql:8.0
    container_name: microservices_riwi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: riwi_db
      MYSQL_PASSWORD: password
    ports:
      - "3399:3306"
    volumes:
      - db_data:/var/lib/mysql # Asegúrate de que este volumen esté definido

volumes:
  db_data: # Definición del volumen
    driver: local

