version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: microservices_riwi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: riwi_db
      MYSQL_PASSWORD: password
    ports:
      - "3399:3306" # Corregí el puerto que tenía "3307doc:3306"
    volumes:
      - db_data:/var/lib/mysql  # Corregí la definición del volumen

volumes:
  db_data:
